#pragma config(Sensor, S1,     luz1,           sensorEV3_Color)
#pragma config(Sensor, S2,     luz2,           sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// variaveis que substitui R - G - B do S1 - S2 - S3
//  R--G--B
int a1,a2,
		b1,b2,
		c1,c2;

// variaveis utilizada na soma e multiplicacao dos valores da calibracao
int abc1,
		abc2;

// variavel utilizada para substituir o SensorValue - futuramente o arduino
int Dist_Lateral;
int Dist_Frente;

task obterCor(){
	while(true){

		getColorRawRGB(luz1,a1,b1,c1);
		getColorRawRGB(luz2,a2,b2,c2);

		abc1 = (a1) + (b1*4) + (c1);
		abc2 = (a2) + (b2*4) + (c2);

		Dist_Frente = SensorValue(S3);
		Dist_Lateral = SensorValue(S4);

	}//WHILLE TRUE
}//TASK OBTERCOR

task main(){
	startTask(obterCor);
	while(true){

		displayCenteredBigTextLine(1,"cor1: %d",abc1);
		displayCenteredBigTextLine(3,"cor2: %d",abc2 );
		displayCenteredBigTextLine(7,"Dist_F: %d",Dist_Frente);
		displayCenteredBigTextLine(9,"Dist_L: %d",Dist_Lateral);

	}
}
